In [ ]:
1D_array=[1,2,3] # 1D array
2D_array=([1,2,3],[4,5,6]) #2D array
3D_array=([1,2,3],[4,5,6][7,8,9],[10,11,12],[13,14,15],[16,17,18],[19,20,21],[22,23,24],[25,26,27] #3D array

In [25]:
arr= [1,2,3,4,5]
type(arr)

list

In [15]:
import numpy as np # Importing NumPy

In [29]:
array1= np.array(arr) # Converting list to array
array1

array([1, 2, 3, 4, 5])

In [31]:
  type(array1)

numpy.ndarray

In [41]:
array1.ndim # To check dimension of the array

1

In [43]:
array1.shape # To check shape of the array

(5,)

In [53]:
arr2=[[1,2,3],[4,5,6],[7,8,9]]

In [55]:
array2=np.array(arr2)
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
arr3= [[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18],[19,20,21],[22,23,24],[25,26,27]]
array3=np.array(arr3)
array3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [61]:
array3.shape

(9, 3)

In [63]:
array3.ndim

2

In [69]:
# Mean

mean_id= np.mean(array3)
mean_id

14.0

In [71]:
mean= np.mean(array1)
mean

3.0

In [73]:
# Medican

median= np.median(array2)
median

5.0

In [75]:

# Standard Deviation

std= np.std(array3)
std

7.788880963698615

In [79]:
arr1= np.array([1,2,3])
arr2= np.array([4,5,6])

In [83]:
arr2

array([4, 5, 6])

In [85]:
arr1

array([1, 2, 3])

In [89]:
sum_arr= arr1+arr2 #Sum matrix
sum_arr

array([5, 7, 9])

In [91]:
dif_arr= arr2-arr1 # Difference
dif_arr

array([3, 3, 3])

In [93]:
mul_arr= arr1*arr2 # Multiplication
mul_arr

array([ 4, 10, 18])

In [95]:
sqrt_arr= np.sqrt(arr1) # Square root
sqrt_arr

array([1.        , 1.41421356, 1.73205081])

In [151]:
x= np.arange(0,10,1) # Range and step up
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
arr6= np.array([[1,2,3],[4,5,6]])
print("original array:")
print(arr6)
print("add 10 to each element:")
print(arr6+10)

original array:
[[1 2 3]
 [4 5 6]]
add 10 to each element:
[[11 12 13]
 [14 15 16]]


In [105]:
print("element at row 1, column 2:",arr6[1,2]) #Slicing

element at row 1, column 2: 6


In [117]:
print("1st row:",arr6[0,:])

1st row: [1 2 3]


In [121]:
print("1st row:",arr6[1,:])

1st row: [4 5 6]


In [123]:
arr6[1,1] # To find value 5

5

In [129]:
arr6[:,2]

array([3, 6])

In [133]:
arr8= np.arange(12)
arr8

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [137]:
reshaped= arr8.reshape(3,4) # Reshape
reshaped

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [139]:
reshaped1= arr8.reshape(3,4)
reshaped1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [141]:
reshaped2= arr8.reshape(2,2) 

ValueError: cannot reshape array of size 12 into shape (2,2)

In [143]:
# Matrix Multiplication
a= np.array([[1,2],[3,4]])
b= np.array([[5,6],[7,8]])
print("Matrix multiplication:")
print(np.dot(a,b))

Matrix multiplication:
[[19 22]
 [43 50]]


In [145]:
random_arr=np.random.randint(1,12,(3,3)) # Random array
print('Random 3*3 array:')
print(random_arr)


Random 3*3 array:
[[ 3  2  6]
 [11 11  8]
 [ 9 10  1]]


In [149]:
random_arr1=np.random.rand(3,3)
print(random_arr1)

[[0.99796646 0.10335306 0.872625  ]
 [0.9262124  0.38291835 0.95930132]
 [0.45164194 0.15163469 0.78343665]]


In [7]:
y = np.random.randint(1, 1000, (5, 5))   # To create new dataset
y 

array([[113, 961, 496, 412,  70],
       [531, 692, 697, 646, 746],
       [823, 662, 586, 757, 194],
       [906,  95, 621, 154, 811],
       [398, 753, 873, 626, 469]])

In [5]:
import numpy as np 

In [9]:
y1 = np.random.randint(2, 1000, (5, 5)) 
y1

array([[682,  98, 227, 511, 765],
       [526, 369, 188, 521, 990],
       [859, 426, 142, 410, 860],
       [178, 956, 182, 504, 530],
       [567, 736, 146, 468, 485]])

In [11]:
c = 45.57                       # To round off value
res = np.round(c)
res

46.0

In [13]:
e = 45.56     
res1 = np.floor(e)
res1

45.0

In [15]:
d = 45.01
np.ceil(d)

46.0